#!/bin/zsh

typeset -A opt_args

# method to comp sub_cmd
# argument 1: the absolute path of current folder
# argument 2: the sub-cmd
#
comp_by_sub_cmd() {
  local sub_cmd=`source $AHACK_HOME/util/subcmd $1 $2`

  if [[ -a $sub_cmd ]] then
    shift
    shift
    _foo $sub_cmd "$@"
  else
    return
  fi
}

# example: "_comp_a_cmd /tmp/abc p-cmd- 6", and there is a p-cmd-def folder
_comp_a_cmd() {
  local dir=$1 # /tmp/abc
  local prefix=$2 # p-cmd-
  local start=`expr $3 + 1` # 7, TODO: get it from $prefix
  for cmddir in $dir/$prefix*/; do
    local s=$(echo `basename $cmddir`':' | cut -c $start-) # def:
    if [[ -a $cmddir/desc ]]; then
      local desc=''
      desc=$(cat $cmddir/desc)
      s=$(echo $s$desc) # def:this is desc
    fi
    subCmds=($subCmds $s)
  done
}

comp_with_sub_cmds() {
  local subCmds; subCmds=()

  _comp_a_cmd $1 'cmd-' 4
  _comp_a_cmd $1 'p-cmd-' 6
  _comp_a_cmd $1 'a-cmd-' 6

  _describe -t subCmds 'command' subCmds && ret=0
}

_foo() {
  local _cmd=$1/_cmd
  if [[ -a $_cmd ]]; then
    shift
    source $_cmd "$@"
  elif (( $# > 1 )); then
    comp_by_sub_cmd "$@"
  else
    comp_with_sub_cmds $1
  fi
}

local n=`expr ${#words} - 1`
_foo `dirname $0` $words[2,n]

