#!/bin/zsh
local mydir=`dirname $0`
if (( $# == 0 )); then
  local commands; commands=()

  for dir in $mydir/cmd-*/; do
    local bn=`basename $dir`
    bn=`echo $bn | cut -c 5-`
    commands+=$bn':'
  done

  for dir in $mydir/p-cmd-*/; do
    local bn=`basename $dir`
    bn=`echo $bn | cut -c 7-`
    commands+=$bn':'
  done

  #TODO: for alias

  _describe -t commands 'command' commands && ret=0
else
  echo 'OHHH'
fi

