#!/bin/zsh

# method to call sub_cmd
# argument 1: the absolute path of current folder
# argument 2: the sub-cmd
# argument 3: the arguments for sub-cmd
# 
# example: 'source ./call_sub_cmd /tmp/abc def x y z' will try to execute
#   - $sub_cmd x y z
# the $sub_cmd is determined by $AHACK_HOME/util/subcmd script
#
call_sub_cmd() {
  local sub_cmd=`source $AHACK_HOME/util/subcmd $1 $2`

  if [[ ! -a $sub_cmd ]] then
    echo 'no such file:' $sub_cmd
    return
  else
    shift
    shift
    source $sub_cmd "$@"
  fi
}

source `dirname $0`/cmd "$@"
