#!/bin/zsh

# $1 : current location
# $2+: arguments
call_sub_cmd() {
  local dir=$1
  shift # now $@ are real arguments

  ### echo for debug purpose only ###
  # echo "call_sub_cmd called: " $dir $@
  ### echo for debug purpose only ###

  # 0. call cmd-mypre
  local cmd=`echo $dir/'cmd-mypre'`
  if [[ -a $cmd ]] then
    source $cmd
  fi

  # 1. if has argument and cmd-**/p-cmd-**/a-cmd-** exist,
  # call cmd-**/p-cmd-**/a-cmd-**, and return
  if (( $# > 0 )); then
    local sub_dir=`source $AHACK_HOME/util/subcmd $dir $1`
    if [[ -a $sub_dir ]] then
      shift
      call_sub_cmd $sub_dir "$@"
      return
    fi
  fi

  # 2. if cmd-$# exist, call it, and return
  cmd=`echo $dir/'cmd-'$#`
  if [[ -a $cmd ]] then
    source $cmd "$@"
    return
  fi

  # 3. if cmd exist, call it, and return
  cmd=$dir/cmd
  if [[ -a $cmd ]] then
    source $cmd "$@"
    return
  fi

  # 4. finally we cannot handle it, print error, and return
  echo can not handle "$dir" "$@"
}

call_sub_cmd `dirname $0` "$@"
