#!/bin/zsh

local aliasFile=`pwd`/.ahack.alias

if (( $# == 0 )); then
  echo "error - argument needed"
  return
fi

function removeAlias() {
  if [[ -a $aliasFile ]]; then
    sed -i '' -e '/^'$1'=/d' $aliasFile
  fi
}

case $1 in
# add your codes here
  *)
     call_sub_cmd `dirname $0` $@
     ;;
esac
