#!/bin/zsh
if (( $# == 0 )); then
  echo "error - argument needed"
  return
elif (( $# == 1 )); then
  local dir='/tmp/ahack/dex2jar'
  mkdir -p $dir
  cd $dir
  sh `dirname $0`/dex2jar-2.0/d2j-dex2jar.sh $1
fi

case $1 in
# add your codes here
  *)
     call_sub_cmd `dirname $0` $@
     ;;
esac
