#!/bin/zsh

local mydir=${0:a:h}
aliasImpl() {
  local aliasFileName=.alias
  if [[ ! -a $aliasFileName ]] then
    touch $aliasFileName
  fi

  if (( $# == 0 )) then
    cat $aliasFileName
  elif (( $# == 1)) then
    #TODO: error if $1 has blank
    cat $aliasFileName | grep $1
  else
    #TODO: error if $1 has blank
    #TODO: error if $2 has blank
    sed -i '' -e '/^'$1'=/d' $aliasFileName # delete original ones
    echo $1'='$2 >> $aliasFileName # write alias
  fi
}

aliasImpl $@
