#!/bin/zsh

if (( $# == 0 )); then
  local myCmds; myCmds=()
  comp_with_sub_cmds `dirname $0` $myCmds

elif (( $# == 1 )); then
  local p=$(sp_dir_of_pkg $1)
  local myCmds; myCmds=(`adb shell ls $p`)
  comp_with_sub_cmds `dirname $0` $myCmds

else
  comp_by_sub_cmd `dirname $0` "$@"
fi
