#!/bin/zsh
if (( $# == 0 )); then
  echo "error - argument needed"
  return
fi

local p=$(sp_dir_of_pkg $1)
case $# in
  1)
    adb shell ls -l $p
    return
    ;;
  2)
    local p=$p$2
    if [[ ! $p == *.xml ]]; then
      p=$p.xml
    fi
    adb shell cat $p
    return
    ;;
  3)
    local p=$p$2
    if [[ ! $p == *.xml ]]; then
      p=$p.xml
    fi
    adb shell cat $p | grep $3
    return
    ;;
    
esac

case $1 in
  # add your codes here
  *)
  call_sub_cmd `dirname $0` $@
  ;;
esac
