#!/bin/zsh
function build_and_push_root_certificate() {
    # ensure we are able to write to device /system/..., otherwise no need to do other things.
    adb push /tmp/test /system/etc/security/cacerts/test 1> /dev/null 2> /dev/null
    if [ $? -eq 0 ]; then
        adb shell rm /system/etc/security/cacerts/test
    else
        adb root
        adb remount
        adb push /tmp/test /system/etc/security/cacerts/test 1> /dev/null 2> /dev/null
        if [ $? -eq 0 ]; then
            adb shell rm /system/etc/security/cacerts/test
        else
            echo either you need to root the device, or to make /system writable
            return
        fi
    fi

    hash=/tmp/`openssl x509 -inform PEM -subject_hash -in $1 | head -1`.0
    cat $1 > $hash
    openssl x509 -inform PEM -text -in $1 -out /dev/null >> $hash

    adb push  $hash /system/etc/security/cacerts/
    adb reboot

    rm $hash
}
