#!/bin/zsh

ahackImpl() {

  if (( $# == 0 )) then
    echo 'arguments needed.'
    return
  fi

  local v=$1
  local p=/data/data/$v/shared_prefs/

  if (( $# == 1 )) then
    adb shell ls -l $p
    return
  fi

  v=$2
  p=$p/$v
  if (( $# == 2 )) then
    adb shell cat $p
    return
  fi

  v=$3
  if (( $# == 3 )) then
    adb shell cat $p | grep $v
    return
  fi

  echo 'nothing to do'
}

ahackImpl $@
