#!/bin/zsh
if (( $# == 1 )); then
  local dir='/tmp/ahack/apktool/'
  mkdir -p $dir
  rm -rf $dir
  java -jar `dirname $0`/apktool_2.1.0.jar d $1 -o $dir
  cd $dir
  return
fi

case $1 in
# add your codes here
  *)
     call_sub_cmd `dirname $0` $@
     ;;
esac
