#!/bin/zsh

goto_sub_cmd() {
  local sub_cmd=`source $AHACK_HOME/util/subcmd $1 $2`

  if [[ ! -a $sub_cmd ]] then
    cd $1
    return
  else
    shift
    shift
    goto_sub_cmd $sub_cmd "$@"
  fi
}

goto_sub_cmd $AHACK_HOME "$@"
