#!/bin/zsh
if (( $# == 0 )); then
  cd $AHACK_HOME
  return
fi

goto_sub_cmd() {
  local sub_cmd=`source $AHACK_HOME/util/subcmd $1 $2`

  if [[ ! -a $sub_cmd ]] then
    cd $1
    return
  else
    local sub_dir=`dirname $sub_cmd`
    shift
    shift
    goto_sub_cmd $sub_dir "$@"
  fi
}

goto_sub_cmd $AHACK_HOME "$@"
return

case $1 in
# add your codes here
  *)
     call_sub_cmd `dirname $0` $@
     ;;
esac
